a52sxq: remove non-existent QCA CLD module from modules.list
The module is actually called "qca_cld3_wlan.ko"

ERROR: qca_cld3_qca6750.ko was not found in the kernel modules intermediates dir, module load list must be corrected

Change-Id: I260f800a86d862b50845ec9cb54150348010ea27